//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _02.WcfServiceDayAsString.ConsoleClient.ServiceReferenceDayAsString {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/_01.WcfServiceDayAsString.Console")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceDayAsString.IServiceDayAsString")]
    public interface IServiceDayAsString {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDayAsString/PrintDayAsString", ReplyAction="http://tempuri.org/IServiceDayAsString/PrintDayAsStringResponse")]
        string PrintDayAsString(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDayAsString/PrintDayAsString", ReplyAction="http://tempuri.org/IServiceDayAsString/PrintDayAsStringResponse")]
        System.Threading.Tasks.Task<string> PrintDayAsStringAsync(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDayAsString/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IServiceDayAsString/GetDataUsingDataContractResponse")]
        _02.WcfServiceDayAsString.ConsoleClient.ServiceReferenceDayAsString.CompositeType GetDataUsingDataContract(_02.WcfServiceDayAsString.ConsoleClient.ServiceReferenceDayAsString.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDayAsString/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IServiceDayAsString/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<_02.WcfServiceDayAsString.ConsoleClient.ServiceReferenceDayAsString.CompositeType> GetDataUsingDataContractAsync(_02.WcfServiceDayAsString.ConsoleClient.ServiceReferenceDayAsString.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceDayAsStringChannel : _02.WcfServiceDayAsString.ConsoleClient.ServiceReferenceDayAsString.IServiceDayAsString, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceDayAsStringClient : System.ServiceModel.ClientBase<_02.WcfServiceDayAsString.ConsoleClient.ServiceReferenceDayAsString.IServiceDayAsString>, _02.WcfServiceDayAsString.ConsoleClient.ServiceReferenceDayAsString.IServiceDayAsString {
        
        public ServiceDayAsStringClient() {
        }
        
        public ServiceDayAsStringClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceDayAsStringClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDayAsStringClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDayAsStringClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string PrintDayAsString(System.DateTime date) {
            return base.Channel.PrintDayAsString(date);
        }
        
        public System.Threading.Tasks.Task<string> PrintDayAsStringAsync(System.DateTime date) {
            return base.Channel.PrintDayAsStringAsync(date);
        }
        
        public _02.WcfServiceDayAsString.ConsoleClient.ServiceReferenceDayAsString.CompositeType GetDataUsingDataContract(_02.WcfServiceDayAsString.ConsoleClient.ServiceReferenceDayAsString.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<_02.WcfServiceDayAsString.ConsoleClient.ServiceReferenceDayAsString.CompositeType> GetDataUsingDataContractAsync(_02.WcfServiceDayAsString.ConsoleClient.ServiceReferenceDayAsString.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
