//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IServiceStringOccurrencesCounter")]
public interface IServiceStringOccurrencesCounter
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStringOccurrencesCounter/CountStringOccurrences", ReplyAction="http://tempuri.org/IServiceStringOccurrencesCounter/CountStringOccurrencesRespons" +
        "e")]
    int CountStringOccurrences(string text, string pattern);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStringOccurrencesCounter/CountStringOccurrences", ReplyAction="http://tempuri.org/IServiceStringOccurrencesCounter/CountStringOccurrencesRespons" +
        "e")]
    System.Threading.Tasks.Task<int> CountStringOccurrencesAsync(string text, string pattern);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IServiceStringOccurrencesCounterChannel : IServiceStringOccurrencesCounter, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ServiceStringOccurrencesCounterClient : System.ServiceModel.ClientBase<IServiceStringOccurrencesCounter>, IServiceStringOccurrencesCounter
{
    
    public ServiceStringOccurrencesCounterClient()
    {
    }
    
    public ServiceStringOccurrencesCounterClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ServiceStringOccurrencesCounterClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServiceStringOccurrencesCounterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServiceStringOccurrencesCounterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public int CountStringOccurrences(string text, string pattern)
    {
        return base.Channel.CountStringOccurrences(text, pattern);
    }
    
    public System.Threading.Tasks.Task<int> CountStringOccurrencesAsync(string text, string pattern)
    {
        return base.Channel.CountStringOccurrencesAsync(text, pattern);
    }
}
