//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _04.TodoLists
{
    using System;
    using System.Collections.Generic;
    
    public partial class TodoList
    {
        public int TodoListId { get; set; }
        public string Title { get; set; }
        public string Text { get; set; }
        public System.DateTime LastChangeDate { get; set; }
        public int CategoryId { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
